import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        // Browser globals (MAIN world inject.js)
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        URL: "readonly",
        Blob: "readonly",
        Set: "readonly",
        Map: "readonly",
        Promise: "readonly",
        MutationObserver: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        Error: "readonly",
        Date: "readonly",
        Math: "readonly",
        JSON: "readonly",
        console: "readonly",
        Intl: "readonly",
        CSS: "readonly",
        Float32Array: "readonly",
        Uint8Array: "readonly",

        // DOM APIs
        HTMLElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLLinkElement: "readonly",
        HTMLAnchorElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        Screen: "readonly",
        Storage: "readonly",
        CanvasRenderingContext2D: "readonly",
        WebGLRenderingContext: "readonly",
        WebGL2RenderingContext: "readonly",
        OffscreenCanvas: "readonly",
        AudioContext: "readonly",
        OfflineAudioContext: "readonly",
        webkitAudioContext: "readonly",
        AudioBuffer: "readonly",
        AnalyserNode: "readonly",
        AudioNode: "readonly",
        RTCPeerConnection: "readonly",
        RTCRtpSender: "readonly",
        RTCRtpReceiver: "readonly",
        WebSocket: "readonly",
        Worker: "readonly",
        SharedWorker: "readonly",
        SharedArrayBuffer: "readonly",
        Atomics: "readonly",
        XMLHttpRequest: "readonly",
        MediaDevices: "readonly",
        MediaRecorder: "readonly",
        HTMLMediaElement: "readonly",
        VideoDecoder: "readonly",
        AudioDecoder: "readonly",
        SubtleCrypto: "readonly",
        PerformanceResourceTiming: "readonly",
        WebAssembly: "readonly",
        Permissions: "readonly",
        Notification: "readonly",
        NetworkInformation: "readonly",
        NavigatorUAData: "readonly",
        Navigator: "readonly",
        SpeechSynthesis: "readonly",
        SpeechSynthesisUtterance: "readonly",
        PerformanceObserver: "readonly",
        Performance: "readonly",
        performance: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        Keyboard: "readonly",
        GPU: "readonly",
        GPUAdapter: "readonly",
        Bluetooth: "readonly",
        USB: "readonly",
        Serial: "readonly",
        HID: "readonly",
        StorageManager: "readonly",
        VisualViewport: "readonly",
        CredentialsContainer: "readonly",
        IDBFactory: "readonly",
        IDBDatabase: "readonly",
        IDBObjectStore: "readonly",
        EventTarget: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        PointerEvent: "readonly",
        Touch: "readonly",
        ServiceWorkerContainer: "readonly",
        ServiceWorkerRegistration: "readonly",
        CacheStorage: "readonly",
        BroadcastChannel: "readonly",
        Clipboard: "readonly",
        Geolocation: "readonly",
        WakeLock: "readonly",
        IdleDetector: "readonly",
        PushManager: "readonly",
        FileSystemHandle: "readonly",
        PublicKeyCredential: "readonly",
        PaymentRequest: "readonly",
        DeviceOrientationEvent: "readonly",
        DeviceMotionEvent: "readonly",
        Window: "readonly",
        Document: "readonly",
        FontFace: "readonly",
        ApplePaySession: "readonly",

        // Chrome extension APIs
        chrome: "readonly",
        browser: "readonly",
        speechSynthesis: "readonly",
      },
    },
    rules: {
      // Errors
      "no-undef": "error",
      "no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
      }],
      "no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-constant-condition": ["error", { checkLoops: false }],

      // Performance footguns
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",

      // Style (warnings, not errors)
      "no-var": "warn",
      "prefer-const": ["warn", { destructuring: "all" }],
      "eqeqeq": ["warn", "smart"],
      "no-throw-literal": "warn",
    },
  },
  {
    // Popup/background/bridge/compare use chrome.* APIs
    files: ["src/popup.js", "src/background.js", "src/bridge.js", "src/compare.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        URL: "readonly",
        Blob: "readonly",
        Set: "readonly",
        Map: "readonly",
        Promise: "readonly",
        CustomEvent: "readonly",
        Date: "readonly",
        JSON: "readonly",
        console: "readonly",
        chrome: "readonly",
        browser: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        FileReader: "readonly",
        alert: "readonly",
        CompressionStream: "readonly",
        DecompressionStream: "readonly",
        Response: "readonly",
        btoa: "readonly",
        atob: "readonly",
      },
    },
  },
  {
    // Hook modules receive all helpers via destructuring but each module
    // only uses a subset — suppress unused param warnings for these files
    files: ["src/hooks/*.js"],
    rules: {
      "no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        args: "none", // don't warn about unused function params in hooks
      }],
    },
  },
  {
    ignores: ["dist/", "node_modules/"],
  },
];
